version: '3.8'
services:
  express:
    image: scholla
    container_name: scholla
    environment:
      API_JWTKEY: yyfn320as27pundlhu9ns4qd87udyi
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js